{{- if eq .Values.jaeger.storage.type "elasticsearch" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-elasticsearch
  labels:
    name: jaeger-elasticsearch
    app.kubernetes.io/name: jaeger-elasticsearch
    app.kubernetes.io/instance: {{ cat "jaeger-elasticsearch-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.rollover.labels }}
      {{- toYaml .Values.elasticsearch.rollover.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.rollover.annotations }}
  annotations:
    {{- toYaml .Values.elasticsearch.rollover.annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ include "elasticsearch.userName" . | b64enc}}
  password: {{ include "elasticsearch.password" . | b64enc}}
{{- end }}
