{{- if .Values.elasticsearch.indexCleaner.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-index-cleaner
  labels:
    name: {{ .Values.jaeger.serviceName }}-index-cleaner
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-index-cleaner
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.indexCleaner.labels }}
      {{- toYaml .Values.elasticsearch.indexCleaner.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.indexCleaner.annotations }}
  annotations:
    {{- toYaml .Values.elasticsearch.indexCleaner.annotations | nindent 4 }}
  {{- end }}
{{- end }}
