{{- if .Values.elasticsearch.lookback.install }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.jaeger.serviceName }}-lookback
  labels:
    name: {{ .Values.jaeger.serviceName }}-lookback
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-lookback
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-lookback-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.lookback.labels }}
      {{- toYaml .Values.elasticsearch.lookback.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.lookback.annotations }}
  annotations:
    {{- toYaml .Values.elasticsearch.lookback.annotations | nindent 4 }}
  {{- end }}
spec:
  concurrencyPolicy: {{ .Values.elasticsearch.lookback.concurrencyPolicy }}
  schedule: {{ .Values.elasticsearch.lookback.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.elasticsearch.lookback.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.elasticsearch.lookback.failedJobsHistoryLimit }}
  suspend: false
  jobTemplate:
    spec:
      {{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.GitVersion }}
      ttlSecondsAfterFinished: {{ .Values.elasticsearch.lookback.ttlSecondsAfterFinished }}
      {{- end }}
      template:
        metadata:
          {{- if .Values.elasticsearch.lookback.annotations }}
          annotations:
            {{- toYaml .Values.elasticsearch.lookback.annotations | nindent 12 }}
          {{- end }}
          labels:
            name: {{ .Values.jaeger.serviceName }}-lookback
            app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-lookback
            app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-lookback-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
            app.kubernetes.io/component: jaeger
            {{- include "jaeger.commonLabels" . | nindent 12 }}
            app.kubernetes.io/managed-by: Helm
            {{- if .Values.elasticsearch.lookback.labels }}
              {{- toYaml .Values.elasticsearch.lookback.labels | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.jaeger.serviceName }}-lookback
          securityContext:
            {{- include "elasticsearch.lookback.securityContext" . }}
          restartPolicy: OnFailure
          {{- if .Values.elasticsearch.lookback.affinity }}
          affinity:
            {{- toYaml .Values.elasticsearch.lookback.affinity | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.lookback.nodeSelector }}
          nodeSelector:
            {{- toYaml .Values.elasticsearch.lookback.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.lookback.tolerations }}
          tolerations:
            {{- toYaml .Values.elasticsearch.lookback.tolerations | nindent 12 }}
          {{- end }}
          {{- with .Values.elasticsearch.lookback.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.elasticsearch.lookback.priorityClassName }}
          priorityClassName: {{ .Values.elasticsearch.lookback.priorityClassName }}
          {{- end }}
          containers:
          - name: {{ .Values.elasticsearch.lookback.name }}
            image: {{ template "rollover.image" . }}
            imagePullPolicy: {{ .Values.elasticsearch.lookback.imagePullPolicy }}
            args:
              - lookback
              - {{ include "elasticsearch.url" . }}
            env:
              - name: ES_SERVER_URLS
                value: {{ include "elasticsearch.url" . }}
              - name: ES_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ if .Values.elasticsearch.existingSecret }}{{ .Values.elasticsearch.existingSecret }}{{- else }}jaeger-elasticsearch{{- end }}
                    key: username
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ if .Values.elasticsearch.existingSecret }}{{ .Values.elasticsearch.existingSecret }}{{- else }}jaeger-elasticsearch{{- end }}
                    key: password
              {{- if .Values.elasticsearch.client.tls.enabled }}
              - name: ES_TLS_ENABLED
                value: {{ .Values.elasticsearch.client.tls.enabled | quote }}
                {{- if or .Values.elasticsearch.client.tls.existingSecret (or .Values.elasticsearch.client.tls.ca .Values.elasticsearch.client.tls.cert .Values.elasticsearch.client.tls.key) }}
              - name: ES_TLS_CA
                value: /es-tls/ca-cert.pem
              - name: ES_TLS_CERT
                value: /es-tls/client-cert.pem
              - name: ES_TLS_KEY
                value: /es-tls/client-key.pem
                {{- else if .Values.elasticsearch.client.tls.insecureSkipVerify }}
              - name: ES_TLS_SKIP_HOST_VERIFY
                value: {{ .Values.elasticsearch.client.tls.insecureSkipVerify | quote }}
                {{- end }}
              {{- end }}
              {{- if .Values.elasticsearch.lookback.extraEnv }}
                {{- toYaml .Values.elasticsearch.lookback.extraEnv | nindent 14 }}
              {{- end }}
            resources:
              {{- toYaml .Values.elasticsearch.lookback.resources | nindent 14 }}
            securityContext:
              {{- include "elasticsearch.lookback.containerSecurityContext" . }}
            volumeMounts:
            {{- if and .Values.elasticsearch.client.tls.enabled (not .Values.elasticsearch.client.tls.insecureSkipVerify) }}
              - name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
                mountPath: "/es-tls/ca-cert.pem"
                subPath: "ca-cert.pem"
                readOnly: true
              - name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
                mountPath: "/es-tls/client-cert.pem"
                subPath: "client-cert.pem"
                readOnly: true
              - name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
                mountPath: "/es-tls/client-key.pem"
                subPath: "client-key.pem"
                readOnly: true
            {{- end }}
            {{- range .Values.elasticsearch.lookback.extraConfigmapMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
            {{- range .Values.elasticsearch.lookback.extraSecretMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                subPath: {{ .subPath }}
                readOnly: {{ .readOnly }}
            {{- end }}
          volumes:
          {{- if and .Values.elasticsearch.client.tls.enabled (not .Values.elasticsearch.client.tls.insecureSkipVerify) }}
            - name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
              secret:
                secretName: {{ template "elasticsearch.tls.secretName" . }}
          {{- end }}
          {{- range .Values.elasticsearch.lookback.extraConfigmapMounts }}
            - name: {{ .name }}
              configMap:
                name: {{ .configMap }}
          {{- end }}
          {{- range .Values.elasticsearch.lookback.extraSecretMounts }}
            - name: {{ .name }}
              secret:
                secretName: {{ .secretName }}
        {{- end }}
{{- end }}
