{{- if .Values.elasticsearch.lookback.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-lookback
  labels:
    {{- $name := printf "%s-lookback" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "jaeger") | nindent 4 }}
    {{- if .Values.elasticsearch.lookback.labels }}
      {{- toYaml .Values.elasticsearch.lookback.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.lookback.annotations }}
  annotations:
    {{- toYaml .Values.elasticsearch.lookback.annotations | nindent 4 }}
  {{- end }}
{{- end }}
