{{- if eq .Values.jaeger.storage.type "elasticsearch" }}
{{- if not .Values.elasticsearch.client.tls.existingSecret }}
{{- if or .Values.elasticsearch.client.tls.ca .Values.elasticsearch.client.tls.cert .Values.elasticsearch.client.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
  labels:
    name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-elasticsearch-tls-assets
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-elasticsearch-tls-assets-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.rollover.labels }}
      {{- toYaml .Values.elasticsearch.rollover.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.elasticsearch.rollover.annotations }}
    {{- toYaml .Values.elasticsearch.rollover.annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.elasticsearch.client.tls.commonName }}
  commonName: {{ .Values.elasticsearch.client.tls.commonName | b64enc }}
  {{- end }}
  ca-cert.pem: {{ .Values.elasticsearch.client.tls.ca | b64enc }}
  client-cert.pem: {{ .Values.elasticsearch.client.tls.cert | b64enc}}
  client-key.pem: {{ .Values.elasticsearch.client.tls.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
