{{- if eq .Values.proxy.type "oauth2" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: oauth2-token
  labels:
    name: oauth2-token
    app.kubernetes.io/name: oauth2-token
    app.kubernetes.io/instance: {{ cat "oauth2-token-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: query
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  token-secret.yaml: >-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: token
        generic_secret:
          secret:
            inline_string: {{ .Values.proxy.oauth2.clientToken }}
  hmac-secret.yaml: >-
    resources:
      - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
        name: hmac
        generic_secret:
          secret:
            inline_bytes: {{ randAlphaNum 32 | b64enc }}
{{- end }}
