version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
# Go mod bot configurations
- package-ecosystem: "gomod"
  directory: "/readiness-probe"
  schedule:
    interval: "monthly"
  groups:
    k8s.io:
      patterns:
      - "k8s.io/*"
    go.opentelemetry.io:
      patterns:
      - "go.opentelemetry.io/*"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
# Go mod bot configurations
- package-ecosystem: "pip"
  directory: "/integration-tests"
  schedule:
    interval: "monthly"
  groups:
    boto3:
      patterns:
      - "boto*"
    robotframework:
      patterns:
      - "robotframework*"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
# Docker bot configurations
- package-ecosystem: "docker"
  directories:
  - "/readiness-probe"
  - "/integration-tests"
  schedule:
    interval: "monthly"
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
