site_name: Qubership Jaeger
site_description: Jaeger helm charts for Qubership - distributed tracing system
site_url: https://netcracker.github.io/qubership-jaeger

# Repository
repo_name: Netcracker/qubership-jaeger
repo_url: https://github.com/Netcracker/qubership-jaeger
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: en
  palette:
    # Dark theme by default
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Light theme option
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark theme option (default)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  # Advanced features
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
  # Icons and fonts
  favicon: assets/favicon.ico
  icon:
    logo: material/chart-timeline
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  font:
    text: Roboto
    code: Roboto Mono
# Extensions with all requested features
markdown_extensions:
  # Basic extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
      toc_depth: 6
  # Enhanced code highlighting for YAML, JSON, Java, Go, Python
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      pygments_style: default
      noclasses: false
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  # Mermaid diagrams support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Advanced content features
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # Emoji support
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Additional formatting
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.betterem:
      smart_enable: all
# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
# Navigation
nav:
  - Home: README.md
  - Installation: installation.md
  - Configuration:
      - Overview: examples.md
      - Storage:
          - Cassandra: examples/cassandra.md
          - OpenSearch: examples/opensearch.md
      - Authentication: examples/auth.md
      - Networking: examples/networking.md
      - Cloud Providers: examples/cloud.md
      - General Examples: examples/general.md
  - Operations:
      - Observability: observability.md
      - Readiness Probe: readiness-probe.md
      - Maintenance: maintenance.md
      - Performance: performance.md
      - Troubleshooting: troubleshooting.md
