{{- if .Values.elasticsearch.rollover.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-rollover-init
  labels:
    name: {{ .Values.jaeger.serviceName }}-rollover-init
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-rollover-init
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-rollover-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.elasticsearch.rollover.labels }}
      {{- toYaml .Values.elasticsearch.rollover.labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # Must be created before the rollover init hook
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    {{- if .Values.elasticsearch.rollover.annotations }}
      {{- toYaml .Values.elasticsearch.rollover.annotations | nindent 4 }}
    {{- end }}
{{- end }}
