{{- if .Values.elasticsearch.rollover.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-rollover-init
  labels:
    {{- $name := printf "%s-rollover-init" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "jaeger") | nindent 4 }}
    {{- if .Values.elasticsearch.rollover.labels }}
      {{- toYaml .Values.elasticsearch.rollover.labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    # Must be created before the rollover init hook
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    {{- if .Values.elasticsearch.rollover.annotations }}
      {{- toYaml .Values.elasticsearch.rollover.annotations | nindent 4 }}
    {{- end }}
{{- end }}
