{{- if .Values.spark.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-dependencies-sa
  labels:
    {{- $name := "spark-dependencies-sa" -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "jaeger-spark-dependencies") | nindent 4 }}
{{- end }}
