{{- if .Values.spark.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-dependencies-sa
  labels:
    name: spark-dependencies-sa
    app.kubernetes.io/name: spark-dependencies-sa
    app.kubernetes.io/instance: {{ cat "jaeger-spark-dependencies-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-spark-dependencies
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
{{- end }}
