{{- if .Values.spark.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jaeger.serviceName }}-spark-dependencies-truststore-secret
  labels:
    name: {{ .Values.jaeger.serviceName }}-spark-dependencies-truststore-secret
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-spark-dependencies-truststore-secret
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-spark-dependencies-truststore-secret-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: spark-dependencies
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.spark.labels }}
      {{- toYaml .Values.spark.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.spark.annotations }}
  annotations:
    {{- toYaml .Values.spark.annotations | nindent 4 }}
  {{- end }}
data:
  password: {{ if .Values.spark.truststorePassword }}{{ .Values.spark.truststorePassword | toString | b64enc }}{{ else }}{{ randAlphaNum 20 | b64enc }}{{ end }}
{{- end }}
