{{- if and .Values.hotrod.install .Values.hotrod.ingress.install }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.jaeger.serviceName }}-hotrod
  labels:
    name: {{ .Values.jaeger.serviceName }}-hotrod
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-hotrod
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-hotrod-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: hotrod
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.hotrod.labels }}
      {{- toYaml .Values.hotrod.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.hotrod.annotations }}
  annotations:
    {{- toYaml .Values.hotrod.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.hotrod.ingress.className }}
  ingressClassName: {{ .Values.hotrod.ingress.className }}
  {{- end }}
  rules:
    - host: {{ include "hotrod.ingress" . }}
      http:
        paths:
          - path: /
            {{- if semverCompare "<1.21-0" .Capabilities.KubeVersion.GitVersion }}
            backend:
              serviceName: {{ .Values.jaeger.serviceName }}-hotrod
              servicePort: "http"
            {{- else }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.jaeger.serviceName }}-hotrod
                port:
                  name: "http"
            {{- end }}
  {{- if .Values.hotrod.ingress.tls }}
  tls:
    {{- toYaml .Values.hotrod.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
