{{- if .Values.hotrod.install }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.serviceName }}-hotrod
  labels:
    {{- $name := printf "%s-hotrod" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "hotrod") | nindent 4 }}
    {{- if .Values.hotrod.labels }}
      {{- toYaml .Values.hotrod.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.hotrod.annotations }}
  annotations:
    {{- toYaml .Values.hotrod.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: {{ .Values.hotrod.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-hotrod
    app.kubernetes.io/component: hotrod
    {{- if .Values.hotrod.labels }}
      {{- toYaml .Values.hotrod.labels | nindent 4 }}
    {{- end }}
{{- end }}
