{{- if .Values.hotrod.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-hotrod
  labels:
    {{- $name := printf "%s-hotrod" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "hotrod") | nindent 4 }}
    {{- if .Values.hotrod.labels }}
      {{- toYaml .Values.hotrod.labels | nindent 4 }}
    {{- end }}
{{- end }}
