{{- if eq .Values.jaeger.storage.type "cassandra" }}
{{- if not .Values.cassandraSchemaJob.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra-pre-hook
  labels:
    name: jaeger-cassandra-pre-hook
    app.kubernetes.io/name: jaeger-cassandra-pre-hook
    app.kubernetes.io/instance: {{ cat "jaeger-cassandra-pre-hook-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.cassandraSchemaJob.labels }}
      {{- toYaml .Values.cassandraSchemaJob.labels | nindent 4 }}
    {{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-5"
    {{- if .Values.cassandraSchemaJob.annotations }}
      {{- toYaml .Values.cassandraSchemaJob.annotations | nindent 4 }}
    {{- end }}
type: Opaque
data:
  username: {{ include "cassandraSchemaJob.userName" . | b64enc }}
  password: {{ include "cassandraSchemaJob.password" . | b64enc }}
{{- end }}
{{- end }}
