{{- if eq .Values.jaeger.storage.type "cassandra" }}
{{- if not .Values.cassandraSchemaJob.tls.existingSecret }}
{{- if or .Values.cassandraSchemaJob.tls.ca .Values.cassandraSchemaJob.tls.cert .Values.cassandraSchemaJob.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra-tls-pre-hook
  labels:
    name: jaeger-cassandra-tls-pre-hook
    app.kubernetes.io/name: jaeger-cassandra-tls-pre-hook
    app.kubernetes.io/instance: {{ cat "jaeger-cassandra-tls-pre-hook-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.cassandraSchemaJob.labels }}
      {{- toYaml .Values.cassandraSchemaJob.labels | nindent 4 }}
    {{- end }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-5"
    {{- if .Values.cassandraSchemaJob.annotations }}
      {{- toYaml .Values.cassandraSchemaJob.annotations | nindent 4 }}
    {{- end }}
data:
  ca-cert.pem: {{ .Values.cassandraSchemaJob.tls.ca | b64enc }}
  client-cert.pem: {{ .Values.cassandraSchemaJob.tls.cert | b64enc}}
  client-key.pem: {{ .Values.cassandraSchemaJob.tls.key | b64enc }}
  cqlshrc: {{ .Values.cassandraSchemaJob.tls.cqlshrc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
