{{- if and .Values.integrationTests.install .Values.integrationTests.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ .Values.integrationTests.serviceAccount.name }}-service-operator
  labels:
    name: {{ .Values.integrationTests.serviceAccount.name }}-service-operator
    app.kubernetes.io/name: {{ .Values.integrationTests.serviceAccount.name }}-service-operator
    app.kubernetes.io/component: jaeger-integration-tests
    app.kubernetes.io/instance: {{ cat .Values.integrationTests.serviceAccount.name "-service-operator-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - secrets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - statefulsets/scale
      - deployments/scale
      - deployments/status
      - daemonsets/status
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - list
{{- end }}
