{{- if .Values.integrationTests.install -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tests-config
  labels:
    {{- $name := "tests-config" -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "jaeger-integration-tests") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-4"
data:
  {{- if include "jaeger.monitoredImages" . }}
  images: {{ include "jaeger.monitoredImages" . }}
  {{ else }}
  images: ""
  {{ end }}
{{ end }}
