{{- if and .Values.integrationTests.install .Values.integrationTests.statusWriting.enabled }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tracing-tests-write-status
  labels:
    {{- $name := "tracing-tests-write-status" -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "jaeger-integration-tests") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-5"
subjects:
- kind: ServiceAccount
  name: {{ .Values.integrationTests.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: tracing-tests-write-status
  apiGroup: rbac.authorization.k8s.io
{{- end }}
