{{- if and .Values.integrationTests.install .Values.integrationTests.statusWriting.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tracing-tests-write-status
  labels:
    name: tracing-tests-write-status
    app.kubernetes.io/name: tracing-tests-write-status
    app.kubernetes.io/instance: {{ cat "tracing-tests-write-status-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-integration-tests
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments/status
  - daemonsets/status
  verbs:
  - get
  - patch
{{- end }}
