{{- if eq .Values.jaeger.storage.type "cassandra" }}
{{- if not .Values.cassandraSchemaJob.tls.existingSecret }}
{{- if or .Values.cassandraSchemaJob.tls.ca .Values.cassandraSchemaJob.tls.cert .Values.cassandraSchemaJob.tls.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-cassandra-tls
  labels:
    name: jaeger-cassandra-tls
    app.kubernetes.io/name: jaeger-cassandra-tls
    app.kubernetes.io/instance: {{ cat "jaeger-cassandra-tls-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.cassandraSchemaJob.labels }}
      {{- toYaml .Values.cassandraSchemaJob.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.cassandraSchemaJob.annotations }}
  annotations:
    {{- toYaml .Values.cassandraSchemaJob.annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.cassandraSchemaJob.tls.commonName }}
  commonName: {{ .Values.cassandraSchemaJob.tls.commonName | b64enc }}
  {{- end }}
  ca-cert.pem: {{ .Values.cassandraSchemaJob.tls.ca | b64enc }}
  client-cert.pem: {{ .Values.cassandraSchemaJob.tls.cert | b64enc}}
  client-key.pem: {{ .Values.cassandraSchemaJob.tls.key | b64enc }}
  cqlshrc: {{ .Values.cassandraSchemaJob.tls.cqlshrc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
