{{- if .Values.query.install }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.jaeger.serviceName }}-ui-configuration
  labels:
    name: {{ .Values.jaeger.serviceName }}-ui-configuration
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-ui-configuration
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-ui-configuration-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: query
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
data:
  query-ui-config.json: >-
    { "dependencies": {
      "dagMaxNumServices": 200,
      "menuEnabled": true
      },
      "menu":[
        {
          "items":[
            {
              "label":"Documentation",
              "url":"https://www.jaegertracing.io/docs/latest"
            }
          ],
          "label":"About"
        }
      ],
      "monitor": {
        "menuEnabled": false
      }
    }
{{- end }}
