{{- if and .Values.query.install .Values.query.route.install }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-query-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: query
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Values.jaeger.serviceName }}-query
spec:
  port:
    targetPort: http-query
  to:
    kind: Service
    name: {{ .Values.jaeger.serviceName }}-query
    weight: 100
  host: {{ include "query.route" . }}
status:
  ingress: []
{{- end }}
