{{- if .Values.query.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-query
  labels:
    {{- $name := printf "%s-query" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "query") | nindent 4 }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
{{- end }}
