{{- if .Values.query.install }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-query-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: query
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
  name: {{ .Values.jaeger.serviceName }}-query
spec:
  ports:
    {{- if .Values.proxy.install }}
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16688
    - name: envoy-admin
      port: 9901
      protocol: TCP
      targetPort: 9901
    {{- else }}
    - name: http-query
      port: 16686
      protocol: TCP
      targetPort: 16686
    {{- end }}
    - name: admin-http
      port: 16687
      protocol: TCP
      targetPort: 16687
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/component: query
  sessionAffinity: None
  type: ClusterIP
{{- end }}
