{{- if .Values.jaeger.prometheusMonitoring }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.jaeger.serviceName }}-query
  labels:
    name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-query
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-query-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: monitoring     # Keep for monitoring contract
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.query.labels }}
      {{- toYaml .Values.query.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.query.annotations }}
  annotations:
    {{- toYaml .Values.query.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - interval: 30s
      port: admin-http
      path: /metrics
      scheme: http
    {{- if .Values.proxy.install }}
    - interval: 30s
      path: /stats/prometheus
      port: envoy-admin
      scheme: http
    {{- end }}
  jobLabel: k8s
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-query
      app.kubernetes.io/component: query
{{- end }}
