{{- if eq .Values.jaeger.storage.type "remote_grpc" }}
{{- if not .Values.remote_grpc.tls.existingSecret }}
{{- if or .Values.remote_grpc.tls.ca .Values.remote_grpc.tls.cert .Values.remote_grpc.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: jaeger-remotegrpc-tls-assets
  labels:
    name: jaeger-remotegrpc-tls-assets
    app.kubernetes.io/name: jaeger-remotegrpc-tls
    app.kubernetes.io/instance: {{ cat "jaeger-remotegrpc-tls-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.remote_grpc.labels }}
      {{- toYaml .Values.remote_grpc.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.remote_grpc.annotations }}
  annotations:
    {{- toYaml .Values.remote_grpc.annotations | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.remote_grpc.tls.commonName }}
  commonName: {{ .Values.remote_grpc.tls.commonName | b64enc }}
  {{- end }}
  ca-cert.pem: {{ .Values.remote_grpc.tls.ca | b64enc }}
  client-cert.pem: {{ .Values.remote_grpc.tls.cert | b64enc}}
  client-key.pem: {{ .Values.remote_grpc.tls.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
