{{- $otelhttpTlsConfigEnabled := .Values.collector.tlsConfig.otelHttp.enabled }}
{{- $otelgrpcTlsConfigEnabled := .Values.collector.tlsConfig.otelgRPC.enabled }}
{{- $jaegerhttpTlsConfigEnabled := .Values.collector.tlsConfig.jaegerHttp.enabled }}
{{- $jaegergrpcTlsConfigEnabled := .Values.collector.tlsConfig.jaegergRPC.enabled }}
{{- $zipkinTlsConfigEnabled := .Values.collector.tlsConfig.zipkin.enabled }}
{{- if .Values.collector.install }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jaeger.serviceName }}-collector
  labels:
    name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-collector-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: collector
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.collector.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
      app.kubernetes.io/component: collector
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ .Values.jaeger.serviceName }}-collector
        app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
        app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-collector-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: collector
        {{- include "jaeger.commonLabels" . | nindent 8 }}
        {{- if .Values.collector.labels }}
        {{- toYaml .Values.collector.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/managed-by: Helm
      {{- if .Values.collector.annotations }}
      annotations:
        {{- toYaml .Values.collector.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.collector.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "collector.securityContext" . }}
      {{- if .Values.collector.priorityClassName }}
      priorityClassName: {{ .Values.collector.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ .Values.jaeger.serviceName }}-collector
      containers:
        - name: {{ .Values.collector.name }}
          image: {{ template "collector.image" . }}
          imagePullPolicy: {{ .Values.collector.imagePullPolicy }}
          args:
            {{- template "collector.args" . }}
          env:
            {{- /* Section with Cassandra environment variables */}}
            {{- if eq .Values.jaeger.storage.type "cassandra" }}
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "cassandraSchemaJob.secretName" . }}
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "cassandraSchemaJob.secretName" . }}
                  key: password
            {{- /* Section with ElasticSearch/OpenSearch environment variables */}}
            {{- else if eq .Values.jaeger.storage.type "elasticsearch" }}
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.existingSecret | default "jaeger-elasticsearch" }}
                  key: username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.elasticsearch.existingSecret | default "jaeger-elasticsearch" }}
                  key: password
            {{- end }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /status
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          {{- if .Values.readinessProbe.install }}
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: {{ .Values.readinessProbe.periodSeconds | default 10 }}
            successThreshold: 1
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 5 }}
          {{- else }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /status
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          {{- end }}
          ports:
            - containerPort: {{ .Values.collector.zipkinPort }}
              name: zipkin
              protocol: TCP
            - containerPort: 13133
              name: healthcheck
              protocol: TCP
            - containerPort: 14250
              name: thrift-grpc
              protocol: TCP
            - containerPort: 14268
              name: thrift-http
              protocol: TCP
            - containerPort: 4317
              name: otlp-grpc
              protocol: TCP
            - containerPort: 4318
              name: otlp-http
              protocol: TCP
            - containerPort: 5778
              name: sampling-http
              protocol: TCP
            - containerPort: 5779
              name: sampling-grpc
              protocol: TCP
            - containerPort: 8888
              name: metrics
              protocol: TCP
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          securityContext:
            {{- include "collector.containerSecurityContext" . }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/jaeger/sampling
              name: {{ .Values.jaeger.serviceName }}-sampling-configuration-volume
              readOnly: true
            - mountPath: /conf
              name: jaeger-collector-configuration-volume
              readOnly: true
            {{- include "jaeger.certificateVolumeMounts" . | nindent 12 }}
        {{- if .Values.readinessProbe.install }}
        - name: readiness-probe
          image: {{ template "readiness-probe.image" . }}
          imagePullPolicy: {{ .Values.readinessProbe.imagePullPolicy }}
          command: ["/app/probe"]
          args:
            {{- template "readinessProbe.args" . }}
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.readinessProbe.resources | nindent 12 }}
          securityContext:
            {{- include "readinessProbe.containerSecurityContext" . }}
          volumeMounts:
            {{- include "jaeger.certificateVolumeMounts" . | nindent 12 }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ .Values.jaeger.serviceName }}-sampling-configuration-volume
          configMap:
            name: {{ .Values.jaeger.serviceName }}-sampling-configuration
            defaultMode: 420
            items:
              - key: sampling
                path: sampling.json
        - name: {{ .Values.jaeger.serviceName }}-collector-configuration-volume
          configMap:
            name: {{ .Values.jaeger.serviceName }}-collector-configuration
            items:
              - key: config.yaml
                path: config.yaml
            defaultMode: 420
        {{- include "jaeger.certificateVolumes" . | nindent 8 }}
      {{- if .Values.collector.affinity }}
      affinity:
        {{- toYaml .Values.collector.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.collector.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.collector.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.collector.tolerations }}
      tolerations:
        {{- toYaml .Values.collector.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
