{{- $gatewayApi := .Values.collector.gatewayApi | default dict -}}
{{- $grpcRouteSpec := $gatewayApi.grpcRoute | default dict -}}
{{- $hostnames := include "collector.gatewayApi.hosts" (list $ $grpcRouteSpec .Values.collector.ingress.grpc) | fromYamlArray -}}
{{- $defaultRules := list (dict "backendRefs" (list (dict "name" (printf "%s-collector" $.Values.jaeger.serviceName) "port" 4317))) -}}
{{- $rules := $grpcRouteSpec.rules | default $defaultRules -}}
{{- $install := or ($grpcRouteSpec.install | default false) (and .Values.collector.ingress.grpc.install (include "jaeger.gatewayApi.enabled" .)) -}}
{{- if and .Values.collector.install $install (eq ($grpcRouteSpec.kind | default "HTTPRoute") "GRPCRoute") }}
{{- $resourceName := include "collector.httpRoute.resourceName" (list $ "grpc") }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ $resourceName }}
  labels:
    app.kubernetes.io/instance: {{ cat $.Values.jaeger.serviceName "-grpc-collector-" $.Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    {{- include "jaeger.labels" (dict "ctx" $ "name" $resourceName "component" "collector") | nindent 4 }}
    {{- if $grpcRouteSpec.labels }}
      {{- toYaml $grpcRouteSpec.labels | nindent 4 }}
    {{- end }}
  {{- if $grpcRouteSpec.annotations }}
  annotations:
    {{- toYaml $grpcRouteSpec.annotations | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- include "jaeger.gatewayApi.parentRefs" (dict "ctx" $ "parentRefs" $grpcRouteSpec.parentRefs) | nindent 4 }}
  {{- if $hostnames }}
  hostnames:
    {{- include "jaeger.gatewayApi.hostnames" (dict "ctx" $ "hosts" $hostnames) | nindent 4 }}
  {{- end }}
  rules:
    {{- toYaml $rules | nindent 4 }}
{{- end }}
