{{- if not .Values.collector.tlsConfig.existingSecret }}
{{- if and .Values.collector.tlsConfig.generateCerts.enabled (or .Values.collector.tlsConfig.otelHttp.enabled
            .Values.collector.tlsConfig.otelgRPC.enabled
            .Values.collector.tlsConfig.jaegerHttp.enabled
            .Values.collector.tlsConfig.jaegergRPC.enabled
            .Values.collector.tlsConfig.zipkin.enabled) (not .Values.collector.tlsConfig.clusterIssuerName)}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: jaeger-collector-tls-issuer
  labels:
    name: jaeger-collector-tls-issuer
    app.kubernetes.io/name: jaeger-collector-tls-issuer
    app.kubernetes.io/instance: {{ cat "jaeger-collector-tls-issuer-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: collector
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
