{{- if .Values.collector.install }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-collector
  labels:
    name: jaeger-collector
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-collector-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-collector
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jaeger.serviceName }}-collector
roleRef:
  kind: Role
  name: jaeger-collector
  apiGroup: rbac.authorization.k8s.io
{{- end }}
