{{- if .Values.collector.install }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.jaeger.serviceName }}-sampling-configuration
  labels:
    name: {{ .Values.jaeger.serviceName }}-sampling-configuration
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-sampling-configuration
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-sampling-configuration-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: collector
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
data:
  sampling: |
    {
      "default_strategy":{
        "param":1,
        "type":"probabilistic"
      }
    }
{{- end }}
