{{- if not .Values.collector.tlsConfig.existingSecret }}
{{- if .Values.collector.tlsConfig.createSecret }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ default "jaeger-collector-tls-secret" .Values.collector.tlsConfig.newSecretName }}
  labels:
    name: {{ default "jaeger-collector-tls-secret" .Values.collector.tlsConfig.newSecretName }}
    app.kubernetes.io/name: {{ default "jaeger-collector-tls-secret" .Values.collector.tlsConfig.newSecretName }}
    app.kubernetes.io/instance: {{ cat (default "jaeger-collector-tls-secret" .Values.collector.tlsConfig.newSecretName) "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: collector
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
data: {}
stringData:
  {{- if .Values.collector.tlsConfig.createSecret.ca }}
  ca.crt:
    {{- toYaml .Values.collector.tlsConfig.createSecret.ca | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.tlsConfig.createSecret.cert }}
  tls.crt:
    {{- toYaml .Values.collector.tlsConfig.createSecret.cert | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.tlsConfig.createSecret.key }}
  tls.key:
    {{- toYaml .Values.collector.tlsConfig.createSecret.key | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
