{{- if .Values.collector.install }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.jaeger.serviceName }}-collector
  labels:
    {{- $name := printf "%s-collector" .Values.jaeger.serviceName -}}
    {{- include "jaeger.resourceLabels" (dict "ctx" . "name" $name "component" "collector") | nindent 4 }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
{{- end }}
