{{- if .Values.jaeger.prometheusMonitoring }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.jaeger.serviceName }}-collector
  labels:
    name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-collector-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: monitoring     # Keep for monitoring contract
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - interval: 30s
    port: admin-http
    path: /metrics
    scheme: http
  jobLabel: k8s
  selector:
    matchLabels:
      app.kubernetes.io/component: collector
      app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
{{- end }}
