{{- if .Values.collector.install }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.serviceName }}-collector
  labels:
    name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/instance: {{ cat .Values.jaeger.serviceName "-collector-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: collector
    {{- include "jaeger.commonLabels" . | nindent 4 }}
    {{- if .Values.collector.labels }}
      {{- toYaml .Values.collector.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.collector.annotations }}
  annotations:
    {{- toYaml .Values.collector.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- if .Values.collector.zipkinPort }}
    - name: http-zipkin
      port: {{ .Values.collector.zipkinPort }}
      protocol: TCP
      targetPort: zipkin
    {{- end }}
    - name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: c-tchan-trft
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: http-c-binary-trft
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: admin-http
      port: 14269
      protocol: TCP
      targetPort: 14269
    - name: healthcheck
      port: 13133
      targetPort: 13133
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.jaeger.serviceName }}-collector
    app.kubernetes.io/component: collector
  sessionAffinity: None
  type: ClusterIP
{{- end }}
