{{- if .Values.statusProvisioner.install }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: integration-tests-status-provisioner
  labels:
    name: integration-tests-status-provisioner
    app.kubernetes.io/name: integration-tests-status-provisioner
    app.kubernetes.io/instance: {{ cat "integration-tests-status-provisioner-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-integration-tests
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-5"
subjects:
  - kind: ServiceAccount
    name: integration-tests-status-provisioner
roleRef:
  kind: Role
  name: integration-tests-status-provisioner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
