---
name: Build Artifacts

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - '**'
  #   paths-ignore:
  #   - '.github/**'
  #   - 'docs/**'
  #   - 'CODE-OF-CONDUCT.md'
  #   - 'CONTRIBUTING.md'
  #   - 'LICENSE'
  #   - 'README.md'
  #   - 'SECURITY.md'

concurrency:
  group: ${{ format('test-build-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
        - name: jaeger-integration-tests
          file: integration-tests/Dockerfile
          context: integration-tests
        - name: jaeger-readiness-probe
          file: readiness-probe/Dockerfile
          context: readiness-probe
        - name: jaeger-transfer
          file: docker-transfer/Dockerfile
          context: ""
    runs-on: ubuntu-latest
    name: ${{ matrix.component.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
    - name: Build and push
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
      with:
        no-cache: true
        context: ${{ matrix.component.context }}
        file: ${{ matrix.component.file }}
        platforms: linux/amd64
        push: false
