name: Go unit tests
on:
  push: {}
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
jobs:
  test:
    uses: Netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@5abe90f775e97f7fb2d2c2ec96b2f8dc1b73ca65 #v1.3.0
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      go-module-dir: ./readiness-probe
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
