name: Jaeger Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Version'
                required: true
            dry-run:
                type: boolean
                description: 'Dry run'
                required: false
                default: true
            path-to-chart:
                description: 'Path to chart'
                required: true
                default: './charts/qubership-jaeger/Chart.yaml'
            # component:
            #     default:  '[
            #         {"name": "jaeger-integration-tests", "file": "integration-tests/Dockerfile", "context": "integration-tests"},
            #         {"name": "jaeger-readiness-probe", "file": "readiness-probe/Dockerfile", "context": "readiness-probe"},
            #         {"name": "jaeger-transfer", "file": "docker-transfer/Dockerfile", "context": "docker-transfer"}
            #       ]'
            #     description: 'Component to docker build'
            #     required: true

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
        with:
          tag: 'v${{ github.event.inputs.version }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Output result
        run: |
          echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
          echo "Tag name: v${{ github.event.inputs.version }}"

      - name: Fail if tag exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Tag already exists: v${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "Tag already exists: v${{ github.event.inputs.version }}"
          exit 1
  load-docker-build-components:
    needs: [check-tag]
    runs-on: ubuntu-latest
    outputs:
      component: ${{ steps.load_component.outputs.components }}
      platforms: ${{ steps.load_component.outputs.platforms }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Docker Configuration
        id: load_component
        run:  |
          json_type=$(jq -r ".|type" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
          if [ "$json_type" == "array" ]; then
            components=$(jq -c "." "$GITHUB_WORKSPACE/.github/docker-build-config.json")
            platforms="linux/amd64"
          elif [ "$json_type" == "object" ]; then
            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
            platforms=$(jq -c ".platforms | join(\",\")" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
          else
            echo "Invalid docker-build-config.json format"
            exit 1
          fi
          if [ -z "$components" ]; then
            echo "components is empty"
            exit 1
          elif [ -z "$platforms" ]; then
            platforms="linux/amd64"
          fi
          echo "components=${components}" >> $GITHUB_OUTPUT
          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
  change-chart:
    needs: [check-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Change Chart Version Action
        uses: netcracker/qubership-workflow-hub/actions/chart-version@main
        with:
          new-chart-version: ${{ github.event.inputs.version }}
          chart-yaml-path: ${{ github.event.inputs.path-to-chart }}

      - name: Run Commit and Push Action
        uses: Netcracker/qubership-workflow-hub/actions/commit-and-push@main
        with:
          commit_message: "Update chart version to v${{ github.event.inputs.version }}"
  tag:
    needs: [change-chart]
    uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
    with:
      tag-name: "v${{ github.event.inputs.version }}"

  docker-build:
    needs: [tag, load-docker-build-components]
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    with:
      ref: v${{ inputs.version }}
      download-artifact: false
      dry-run: ${{ inputs.dry-run }}
      component: ${{ needs.load-docker-build-components.outputs.component }}
      platforms: ${{ needs.load-docker-build-components.outputs.platforms }}